name: UI Tests Pipeline

on:
  push:
   branches: [ "main" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Install Playwright dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 \
            libatk-bridge2.0-0 \
            libgtk-3-0 \
            libxss1 \
            libasound2t64 \
            libx11-xcb1 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            libgbm1 \
            libpango-1.0-0 \
            libcairo2 \
            libatspi2.0-0

      - name: Run tests (with logs)
        if: github.event_name == 'push'
        run: ./gradlew clean test --parallel --info --stacktrace

      - name: Debug cucumber file
        if: github.event_name == 'push'
        run: |
          echo "---- BUILD CONTENT ----"
          ls -la build/
          echo "---- CUCUMBER JSON ----"
          cat build/cucumber-report.json || echo "FILE NOT FOUND"  

      - name: Import Gherkin scenarios to Xray
        if: github.event_name == 'push'
        run: |
          TOKEN=$(curl -s -X POST "https://xray.cloud.getxray.app/api/v2/authenticate" \
            -H "Content-Type: application/json" \
            -d "{\"client_id\":\"${{ secrets.XRAY_CLIENT_ID }}\",\"client_secret\":\"${{ secrets.XRAY_CLIENT_SECRET }}\"}" | tr -d '"')

          curl -X POST "https://xray.cloud.getxray.app/api/v2/import/feature?projectKey=E2E" \
            -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type: multipart/form-data" \
            -F "file=@src/test/resources/features/homepage.feature"

      - name: Upload results to Xray
        if: github.event_name == 'push'
        run: |
          TOKEN=$(curl -s -X POST "https://xray.cloud.getxray.app/api/v2/authenticate" \
            -H "Content-Type: application/json" \
            -d "{\"client_id\":\"${{ secrets.XRAY_CLIENT_ID }}\",\"client_secret\":\"${{ secrets.XRAY_CLIENT_SECRET }}\"}" | tr -d '"')

          echo '{"info":{"summary":"Automation Execution","description":"Execution from GitHub Actions","project":"E2E"}}' > test-exec.json

          cat test-exec.json

          curl -v -X POST "https://xray.cloud.getxray.app/api/v2/import/execution/cucumber/multipart" \
            -H "Authorization: Bearer $TOKEN" \
            -F "info=@test-exec.json" \
            -F "results=@build/cucumber-report.json"

      - name: Load previous Allure history
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
        continue-on-error: true

      - name: Copy Allure history
        run: |
          mkdir -p build/reports/allure-report/history
          cp -r gh-pages/allure-report/history/* build/reports/allure-report/history/ || true  

      - name: Generate Allure Report
        run: ./gradlew allureReport

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/reports/allure-report