name: UI Tests Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install browsers (Playwright)
        run: |
          chmod +x gradlew
          ./gradlew playwrightInstall

      - name: Run tests
        run: ./gradlew clean test

      - name: Generate Allure Report
        run: ./gradlew allureReport

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: build/reports/allure-report